### PR TITLE
Added tagcloud option to the index page

### PR DESCRIPTION
**Pull request by aytic**
I quite missed that feature in this awesome theme :). 

Added a new setting for the config to display all tags on the index page. 
This will use the hexo helperscript tagcloud().

Preview:
tagcloud_cactus_example

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Missed this too

**Comment by aytic** [comment]
@kezhenxu94 英雄所见略同 ^^

**Comment by alexmufatti** [comment]
Thank you, great feature!

**Comment by probberechts** [comment]
Thanks and I am sorry for the late reply. It is now merged inside the master branch. Though, with a couple of small modifications:
- I've put the tagcloud under the "Writing" section, since that is where it belongs.
- I've modified the `config.yml` variables such that you can use the options defined by <https://hexo.io/docs/helpers.html#tagcloud>.

**Pull request merged**
